name: Build
on: [ push, pull_request ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: 游닌 Checkout
        uses: actions/checkout@v4

      - name: 游닇 Set up Taskfile
        uses: arduino/setup-task@v1

      - name: 游닌 Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: 游닌 Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}

      - name: 游닌 Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          cache-read-only: true

      - name: Disable the Gradle daemon
        run: |
          mkdir -p ~/.gradle
          echo 'org.gradle.daemon=false' >> ~/.gradle/gradle.properties

      - name: 游빍 Run tests
        run: task build:test

      - name: 游눠 Linter
        uses: pre-commit/action@v3.0.0

      - name: 游댣 Build
        run: task build

      - name: 游댏 Log in to Dockerhub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 游냡 Push image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: virginonline/mediasoft
